using System;
using System.Collections.Generic;

namespace MoviesApp.DTO
{
    /// <summary>
    /// Data Transfer Object for creating a new Movie.
    /// </summary>
    public class MovieCreateDto
    {
        /// <summary>
        /// Gets or sets the unique identifier of the movie.
        /// Typically generated by the system.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the name/title of the movie.
        /// This is a required field.
        /// </summary>
        public required string Name { get; set; }

        /// <summary>
        /// Gets or sets the duration of the movie in minutes.
        /// This is a required field.
        /// </summary>
        public required int Duration { get; set; }

        /// <summary>
        /// Gets or sets the rating of the movie (e.g., IMDb rating).
        /// This is an optional field.
        /// </summary>
        public float? Rating { get; set; }

        /// <summary>
        /// Gets or sets the release year of the movie.
        /// This is a required field.
        /// </summary>
        public required int ReleaseYear { get; set; }

        /// <summary>
        /// Gets or sets a description or synopsis of the movie.
        /// This is an optional field.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the name of the director of the movie.
        /// This is a required field.
        /// </summary>
        public required string DirectorName { get; set; }

        /// <summary>
        /// Gets or sets the list of genre IDs associated with the movie.
        /// This is a required field.
        /// </summary>
        public required IList<Guid> Genres { get; set; }

        /// <summary>
        /// Gets or sets the list of language IDs associated with the movie.
        /// This is a required field.
        /// </summary>
        public required IList<Guid> Languages { get; set; }
    }
}
